name: ساخت APK برای اندروید ۸.۱ و ARMv7

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # قابلیت اجرای دستی

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: دریافت کدهای مخزن
      uses: actions/checkout@v4

    - name: نصب JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: دادن دسترسی اجرا به gradlew
      run: chmod +x gradlew

    - name: ساخت فایل APX نهایی (نسخه Release)
      run: ./gradlew assembleRelease

    - name: آپلود خروجی به عنوان Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release-armv7
        path: app/build/outputs/apk/release/*.apk
